try {
    const abc = 123;
    abc = 'abc';
} catch(error) {
    console.log('An error occured, please try again.');
}

console.log('Program keeps on running!');
